# Generated by Django 5.1.6 on 2025-06-26 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the medicine", max_length=100, unique=True
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2, help_text="Price per unit", max_digits=10
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(default=0, help_text="Available stock"),
                ),
            ],
            options={
                "verbose_name": "Medicine",
                "verbose_name_plural": "Medicines",
            },
        ),
        migrations.CreateModel(
            name="MedicineRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(help_text="Requested quantity"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("FULFILLED", "Fulfilled")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                (
                    "fulfilled_quantity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("fulfilled_date", models.DateTimeField(blank=True, null=True)),
                (
                    "fulfilled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="supply.medicine",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicine_requests",
                        to="supply.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicine Request",
                "verbose_name_plural": "Medicine Requests",
            },
        ),
    ]
