# Generated by Django 5.1.6 on 2025-06-27 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0002_medicine_medicinerequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicine",
            options={
                "ordering": ["name"],
                "verbose_name": "Medicine",
                "verbose_name_plural": "Medicines",
            },
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="price_per_unit",
        ),
        migrations.AddField(
            model_name="medicine",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medicine",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
