# Generated by Django 5.1.6 on 2025-06-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0003_alter_medicine_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="medicines/"),
        ),
    ]
