# Generated by Django 5.1.6 on 2025-06-27 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0004_alter_medicine_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
    ]
