# Generated by Django 5.1.6 on 2025-06-27 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0005_medicine_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
    ]
