# Generated by Django 5.1.6 on 2025-06-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0006_alter_medicine_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_id",
            field=models.BigIntegerField(editable=False, unique=True),
        ),
    ]
