# Generated by Django 5.1.6 on 2025-06-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0008_alter_member_member_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_id",
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
