# Generated by Django 5.1.15 on 2026-10-03 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0009_alter_member_member_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicinerequest",
            options={
                "ordering": ["-request_date"],
                "verbose_name": "Medicine Request",
                "verbose_name_plural": "Medicine Requests",
            },
        ),
        migrations.AlterField(
            model_name="medicine",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.01,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="member_id",
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
